// <auto-generated />
namespace PasswordWallet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class user_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_change));
        
        string IMigrationMetadata.Id
        {
            get { return "202012082316047_user_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
